Implement backend management CLI
ictsc/ictsc-regalia pull request #894
Opened 2024-12-25 09:53 UTC by kerthical

ICTSC Regaliaのバックエンドを触れるCLIを作成しました。実質的にcurlの薄いラッパーです。 #893

2025-01-12 10:42 UTC, tosuke requested changes
lint は通る状態にしてからレビューに出してほしいです :bow:

2025-01-12 10:42 UTC, tosuke commented on backend/cmd/ictscli/cmd/team/create.go
> +func init() {
初期化順序がわかりにくくなるので `init` は使わないでほしいです。`func createCmd()`を定義するなどがよさそう

2025-01-12 10:45 UTC, kerthical commented
> lint は通る状態にしてからレビューに出してほしいです :bow: 

lintは通ってませんか…？とはいえコンフリクトの解決とレビュー項目については時間がある時に修正しておきます。

![image](https://github.com/user-attachments/assets/1aa35380-b2bc-4df8-80c1-e4c27de49101)

2025-03-10 00:12 UTC, tosuke commented
対応されないようなので一旦閉じます。ありがとうございました

2025-03-10 00:12 UTC, closed without merging